[book]
authors = ["James"]
language = "en"
multilingual = false
src = "src"
title = "James's personal writings"

[rust]
edition = "2018"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
